In [2]:
import pandas as pd
import numpy as np
import glob
import os
from pathlib import Path

In [3]:
pwd

'/Users/minhtamninale/Documents/Angela/Spots_troubleshooting/3rd_647_as_PPE/Post_processing'

In [4]:
df_early = pd.read_csv('../Early_embryo/Early_conformation_conformation_count.csv')
df_early_new = df_early.drop(columns=['Unnamed: 0'])
df_early_new

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,5.0,12,1,11,0,0,0,1,0
1,14.0,66,6,11,1,0,0,0,2
2,4.0,2,0,1,1,0,0,0,1
3,7.0,24,0,18,0,0,0,0,4
4,1.0,2,0,2,0,0,0,0,0
5,15.0,40,0,2,0,0,0,0,1
6,11.0,1,3,2,2,0,0,2,19
7,12.0,2,3,7,11,0,0,1,34
8,14.0,10,6,17,14,0,1,2,22
9,21.0,0,3,1,2,2,0,3,28
10,22.0,5,3,12,7,1,0,0,30
11,25.0,0,2,5,2,0,0,1,19
12,26.0,14,13,21,19,0,3,1,21
13,27.0,1,5,8,8,1,1,0,19
14,33.0,7,10,10,6,0,1,0,25
15,35.0,0,0,3,1,0,1,0,12
16,40.0,8,4,9,3,1,1,0,11
17,59.0,2,2,5,5,1,1,0,30
18,61.0,0,0,1,0,0,0,0,9
19,62.0,5,3,12,2,0,0,0,14
20,63.0,1,3,4,2,0,0,0,8
21,65.0,0,1,2,0,0,1,0,9
22,72.0,13,7,11,12,2,1,2,20
23,73.0,4,5,5,1,1,0,1,7
24,74.0,0,2,5,2,1,1,0,10

In [5]:
df_late = pd.read_csv('../Late_embryo/Late_conformation_conformation_count.csv')
df_late_new = df_late.drop(columns=['Unnamed: 0'])
df_late_new

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,10.0,19,0,7,1,0,0,0,0
1,19.0,8,0,6,0,1,0,1,0
2,11.0,61,4,6,0,0,0,0,0
3,9.0,19,2,7,1,0,0,0,1
4,13.0,40,0,4,1,0,0,0,0
5,17.0,24,3,7,6,0,0,0,1
6,6.0,24,1,8,3,0,0,0,2
7,2.0,8,1,12,1,0,0,0,3
8,8.0,30,1,3,0,0,0,0,1
9,20.0,0,1,1,0,0,0,0,0
10,9.0,3,2,10,4,2,1,0,23
11,10.0,8,10,20,24,2,4,0,50
12,15.0,2,2,9,4,0,3,0,12
13,16.0,21,9,33,29,4,7,3,64
14,17.0,1,2,9,1,0,5,0,33
15,18.0,2,1,0,3,0,0,1,10
16,19.0,6,2,12,8,0,1,1,23
17,23.0,1,2,14,10,0,1,2,16
18,24.0,2,4,15,17,2,1,0,41
19,30.0,0,4,4,4,0,1,0,30
20,31.0,5,5,1,3,5,1,1,19
21,36.0,11,14,28,28,7,6,3,61
22,38.0,12,10,20,17,2,0,0,16
23,39.0,2,4,7,3,0,1,0,11
24,42.0,11,7,16,18,2,5,2,29

In [6]:
df_YW = pd.concat([df_early_new, df_late_new])

In [7]:
def calculate_category_percentages(dataframe):
    #Exclude Embryo ID in calculation
    columns_to_calculate = dataframe.columns[1:]
    
    # Calculate the sum of each row
    row_sums = dataframe[columns_to_calculate].sum(axis=1)

    # Calculate the percentage of each column for each row by dividing the value of each column by the row sum and multiplying by 100
    category_percentages = dataframe[columns_to_calculate].div(row_sums, axis=0) *100
    
    category_percentages.insert(0, 'Embryo_ID', dataframe['Embryo_ID'])
    return category_percentages

In [8]:
percentage_df = calculate_category_percentages(df_YW)
percentage_df

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,5.0,48.000000,4.000000,44.000000,0.000000,0.000000,0.000000,4.000000,0.000000
1,14.0,76.744186,6.976744,12.790698,1.162791,0.000000,0.000000,0.000000,2.325581
2,4.0,40.000000,0.000000,20.000000,20.000000,0.000000,0.000000,0.000000,20.000000
3,7.0,52.173913,0.000000,39.130435,0.000000,0.000000,0.000000,0.000000,8.695652
4,1.0,50.000000,0.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,15.0,93.023256,0.000000,4.651163,0.000000,0.000000,0.000000,0.000000,2.325581
6,11.0,3.448276,10.344828,6.896552,6.896552,0.000000,0.000000,6.896552,65.517241
7,12.0,3.448276,5.172414,12.068966,18.965517,0.000000,0.000000,1.724138,58.620690
8,14.0,13.888889,8.333333,23.611111,19.444444,0.000000,1.388889,2.777778,30.555556
9,21.0,0.000000,7.692308,2.564103,5.128205,5.128205,0.000000,7.692308,71.794872
10,22.0,8.620690,5.172414,20.689655,12.068966,1.724138,0.000000,0.000000,51.724138
11,25.0,0.000000,6.896552,17.241379,6.896552,0.000000,0.000000,3.448276,65.517241
12,26.0,15.217391,14.130435,22.826087,20.652174,0.000000,3.260870,1.086957,22.826087
13,27.0,2.325581,11.627907,18.604651,18.604651,2.325581,2.325581,0.000000,44.186047
14,33.0,11.864407,16.949153,16.949153,10.169492,0.000000,1.694915,0.000000,42.372881
15,35.0,0.000000,0.000000,17.647059,5.882353,0.000000,5.882353,0.000000,70.588235
16,40.0,21.621622,10.810811,24.324324,8.108108,2.702703,2.702703,0.000000,29.729730
17,59.0,4.347826,4.347826,10.869565,10.869565,2.173913,2.173913,0.000000,65.217391
18,61.0,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,90.000000
19,62.0,13.888889,8.333333,33.333333,5.555556,0.000000,0.000000,0.000000,38.888889
20,63.0,5.555556,16.666667,22.222222,11.111111,0.000000,0.000000,0.000000,44.444444
21,65.0,0.000000,7.692308,15.384615,0.000000,0.000000,7.692308,0.000000,69.230769
22,72.0,19.117647,10.294118,16.176471,17.647059,2.941176,1.470588,2.941176,29.411765
23,73.0,16.666667,20.833333,20.833333,4.166667,4.166667,0.000000,4.166667,29.166667
24,74.0,0.000000,9.523810,23.809524,9.523810,4.761905,4.761905,0.000000,47.619048
0,10.0,70.370370,0.000000,25.925926,3.703704,0.000000,0.000000,0.000000,0.000000
1,19.0,50.000000,0.000000,37.500000,0.000000,6.250000,0.000000,6.250000,0.000000
2,11.0,85.915493,5.633803,8.450704,0.000000,0.000000,0.000000,0.000000,0.000000
3,9.0,63.333333,6.666667,23.333333,3.333333,0.000000,0.000000,0.000000,3.333333
4,13.0,88.888889,0.000000,8.888889,2.222222,0.000000,0.000000,0.000000,0.000000
5,17.0,58.536585,7.317073,17.073171,14.634146,0.000000,0.000000,0.000000,2.439024
6,6.0,63.157895,2.631579,21.052632,7.894737,0.000000,0.000000,0.000000,5.263158
7,2.0,32.000000,4.000000,48.000000,4.000000,0.000000,0.000000,0.000000,12.000000
8,8.0,85.714286,2.857143,8.571429,0.000000,0.000000,0.000000,0.000000,2.857143
9,20.0,0.000000,50.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,9.0,6.666667,4.444444,22.222222,8.888889,4.444444,2.222222,0.000000,51.111111
11,10.0,6.779661,8.474576,16.949153,20.338983,1.694915,3.389831,0.000000,42.372881
12,15.0,6.250000,6.250000,28.125000,12.500000,0.000000,9.375000,0.000000,37.500000
13,16.0,12.352941,5.294118,19.411765,17.058824,2.352941,4.117647,1.764706,37.647059
14,17.0,1.960784,3.921569,17.647059,1.960784,0.000000,9.803922,0.000000,64.705882
15,18.0,11.764706,5.882353,0.000000,17.647059,0.000000,0.000000,5.882353,58.823529
16,19.0,11.320755,3.773585,22.641509,15.094340,0.000000,1.886792,1.886792,43.396226
17,23.0,2.173913,4.347826,30.434783,21.739130,0.000000,2.173913,4.347826,34.782609
18,24.0,2.439024,4.878049,18.292683,20.731707,2.439024,1.219512,0.000000,50.000000
19,30.0,0.000000,9.302326,9.302326,9.302326,0.000000,2.325581,0.000000,69.767442
20,31.0,12.500000,12.500000,2.500000,7.500000,12.500000,2.500000,2.500000,47.500000
21,36.0,6.962025,8.860759,17.721519,17.721519,4.430380,3.797468,1.898734,38.607595
22,38.0,15.584416,12.987013,25.974026,22.077922,2.597403,0.000000,0.000000,20.779221
23,39.0,7.142857,14.285714,25.000000,10.714286,0.000000,3.571429,0.000000,39.285714
24,42.0,12.222222,7.777778,17.777778,20.000000,2.222222,5.555556,2.222222,32.222222

In [9]:
transposed_percentage= percentage_df.T
transposed_percentage

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
Embryo_ID,5.0,14.000000,4.0,7.000000,1.0,15.000000,11.000000,12.000000,14.000000,21.000000,...,18.000000,19.000000,23.000000,24.000000,30.000000,31.0,36.000000,38.000000,39.000000,42.000000
Counts_of_not_touching,48.0,76.744186,40.0,52.173913,50.0,93.023256,3.448276,3.448276,13.888889,0.000000,...,11.764706,11.320755,2.173913,2.439024,0.000000,12.5,6.962025,15.584416,7.142857,12.222222
Counts_3_prime_touch_5_prime,4.0,6.976744,0.0,0.000000,0.0,0.000000,10.344828,5.172414,8.333333,7.692308,...,5.882353,3.773585,4.347826,4.878049,9.302326,12.5,8.860759,12.987013,14.285714,7.777778
Counts_5_prime_touch_PPE,44.0,12.790698,20.0,39.130435,50.0,4.651163,6.896552,12.068966,23.611111,2.564103,...,0.000000,22.641509,30.434783,18.292683,9.302326,2.5,17.721519,25.974026,25.000000,17.777778
Counts_3_prime_touch_PPE,0.0,1.162791,20.0,0.000000,0.0,0.000000,6.896552,18.965517,19.444444,5.128205,...,17.647059,15.094340,21.739130,20.731707,9.302326,7.5,17.721519,22.077922,10.714286,20.000000
Counts_5_prime_middle,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,5.128205,...,0.000000,0.000000,0.000000,2.439024,0.000000,12.5,4.430380,2.597403,0.000000,2.222222
Counts_PPE_middle,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.388889,0.000000,...,0.000000,1.886792,2.173913,1.219512,2.325581,2.5,3.797468,0.000000,3.571429,5.555556
Counts_3_prime_middle,4.0,0.000000,0.0,0.000000,0.0,0.000000,6.896552,1.724138,2.777778,7.692308,...,5.882353,1.886792,4.347826,0.000000,0.000000,2.5,1.898734,0.000000,0.000000,2.222222
Counts_all_touching,0.0,2.325581,20.0,8.695652,0.0,2.325581,65.517241,58.620690,30.555556,71.794872,...,58.823529,43.396226,34.782609,50.000000,69.767442,47.5,38.607595,20.779221,39.285714,32.222222

In [10]:
transposed_percentage.to_csv('YW_overall_percentages.csv')

In [11]:
df_YW_transformed = df_YW.T

In [12]:
df_YW_transformed

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
Embryo_ID,5.0,14.0,4.0,7.0,1.0,15.0,11.0,12.0,14.0,21.0,...,18.0,19.0,23.0,24.0,30.0,31.0,36.0,38.0,39.0,42.0
Counts_of_not_touching,12.0,66.0,2.0,24.0,2.0,40.0,1.0,2.0,10.0,0.0,...,2.0,6.0,1.0,2.0,0.0,5.0,11.0,12.0,2.0,11.0
Counts_3_prime_touch_5_prime,1.0,6.0,0.0,0.0,0.0,0.0,3.0,3.0,6.0,3.0,...,1.0,2.0,2.0,4.0,4.0,5.0,14.0,10.0,4.0,7.0
Counts_5_prime_touch_PPE,11.0,11.0,1.0,18.0,2.0,2.0,2.0,7.0,17.0,1.0,...,0.0,12.0,14.0,15.0,4.0,1.0,28.0,20.0,7.0,16.0
Counts_3_prime_touch_PPE,0.0,1.0,1.0,0.0,0.0,0.0,2.0,11.0,14.0,2.0,...,3.0,8.0,10.0,17.0,4.0,3.0,28.0,17.0,3.0,18.0
Counts_5_prime_middle,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,2.0,0.0,5.0,7.0,2.0,0.0,2.0
Counts_PPE_middle,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,6.0,0.0,1.0,5.0
Counts_3_prime_middle,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,3.0,...,1.0,1.0,2.0,0.0,0.0,1.0,3.0,0.0,0.0,2.0
Counts_all_touching,0.0,2.0,1.0,4.0,0.0,1.0,19.0,34.0,22.0,28.0,...,10.0,23.0,16.0,41.0,30.0,19.0,61.0,16.0,11.0,29.0

In [13]:
def calculate_category_sum(dataframe): 
    categories = ['Embryo_ID','Counts_of_not_touching', 'Counts_3_prime_touch_5_prime', 'Counts_5_prime_touch_PPE',
                  'Counts_3_prime_touch_PPE', 'Counts_5_prime_middle', 'Counts_PPE_middle',
                  'Counts_3_prime_middle', 'Counts_all_touching']    
    row_sums = []
    for _, row in dataframe.iterrows():
        row_sum = row.sum()
        row_sums.append(row_sum)
    row_sums_df = pd.DataFrame({'Category': categories, 'Category_Sum':row_sums})
    return row_sums_df

In [14]:
sum_category = calculate_category_sum(df_YW_transformed)
YW_sum = sum_category.iloc[1:]
YW_sum

                       Category  Category_Sum
1        Counts_of_not_touching         539.0
2  Counts_3_prime_touch_5_prime         173.0
3      Counts_5_prime_touch_PPE         444.0
4      Counts_3_prime_touch_PPE         287.0
5         Counts_5_prime_middle          37.0
6             Counts_PPE_middle          49.0
7         Counts_3_prime_middle          28.0
8           Counts_all_touching         801.0

In [15]:
YW_sum.to_csv('YW_sum.csv')

In [16]:
df_YW_transformed.to_csv('YW_grouped_conformation.csv')

In [17]:
def calculate_column_medians(counts_conformation):
    columns_medians = df_YW.median()
    columns_median_df = pd.DataFrame(columns_medians, columns=['Median'])
    columns_median_df.reset_index(inplace=True)
    columns_median_df.rename(columns={'index': 'Categories'}, inplace=True)
    return columns_median_df

df_YW_median = calculate_column_medians(df_YW)
YW_embryo_median = df_YW_median.drop([0]).reset_index(drop = True)

In [18]:
YW_embryo_median

                     Categories  Median
0        Counts_of_not_touching     5.0
1  Counts_3_prime_touch_5_prime     2.5
2      Counts_5_prime_touch_PPE     7.0
3      Counts_3_prime_touch_PPE     2.5
4         Counts_5_prime_middle     0.0
5             Counts_PPE_middle     0.0
6         Counts_3_prime_middle     0.0
7           Counts_all_touching    12.0

In [19]:
YW_embryo_median.to_csv("YW_embryo_median_conformation_count.csv")