In [2]:
import pandas as pd
import numpy as np
import glob
import os
from pathlib import Path

In [11]:
file_path = '../Early_embryo/Early_percentages.csv'

df_early = pd.read_csv('../Early_embryo/Early_percentages_per_embryo.csv').drop(columns = 'Unnamed: 0')
df_early

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,5.0,48.000000,4.000000,44.000000,0.000000,0.000000,0.000000,4.000000,0.000000
1,14.0,76.744186,6.976744,12.790698,1.162791,0.000000,0.000000,0.000000,2.325581
2,4.0,40.000000,0.000000,20.000000,20.000000,0.000000,0.000000,0.000000,20.000000
3,7.0,52.173913,0.000000,39.130435,0.000000,0.000000,0.000000,0.000000,8.695652
4,1.0,50.000000,0.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,15.0,93.023256,0.000000,4.651163,0.000000,0.000000,0.000000,0.000000,2.325581
6,11.0,3.448276,10.344828,6.896552,6.896552,0.000000,0.000000,6.896552,65.517241
7,12.0,3.448276,5.172414,12.068966,18.965517,0.000000,0.000000,1.724138,58.620690
8,14.0,13.888889,8.333333,23.611111,19.444444,0.000000,1.388889,2.777778,30.555556
9,21.0,0.000000,7.692308,2.564103,5.128205,5.128205,0.000000,7.692308,71.794872
10,22.0,8.620690,5.172414,20.689655,12.068966,1.724138,0.000000,0.000000,51.724138
11,25.0,0.000000,6.896552,17.241379,6.896552,0.000000,0.000000,3.448276,65.517241
12,26.0,15.217391,14.130435,22.826087,20.652174,0.000000,3.260870,1.086957,22.826087
13,27.0,2.325581,11.627907,18.604651,18.604651,2.325581,2.325581,0.000000,44.186047
14,33.0,11.864407,16.949153,16.949153,10.169492,0.000000,1.694915,0.000000,42.372881
15,35.0,0.000000,0.000000,17.647059,5.882353,0.000000,5.882353,0.000000,70.588235
16,40.0,21.621622,10.810811,24.324324,8.108108,2.702703,2.702703,0.000000,29.729730
17,59.0,4.347826,4.347826,10.869565,10.869565,2.173913,2.173913,0.000000,65.217391
18,61.0,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,90.000000
19,62.0,13.888889,8.333333,33.333333,5.555556,0.000000,0.000000,0.000000,38.888889
20,63.0,5.555556,16.666667,22.222222,11.111111,0.000000,0.000000,0.000000,44.444444
21,65.0,0.000000,7.692308,15.384615,0.000000,0.000000,7.692308,0.000000,69.230769
22,72.0,19.117647,10.294118,16.176471,17.647059,2.941176,1.470588,2.941176,29.411765
23,73.0,16.666667,20.833333,20.833333,4.166667,4.166667,0.000000,4.166667,29.166667
24,74.0,0.000000,9.523810,23.809524,9.523810,4.761905,4.761905,0.000000,47.619048

In [4]:
file_path = 'Late_embryo/Early_percentages.csv'

df_late = pd.read_csv('../Late_embryo/Late_percentages_per_embryo.csv').drop(columns = 'Unnamed: 0')
df_late

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,10.0,70.370370,0.000000,25.925926,3.703704,0.000000,0.000000,0.000000,0.000000
1,19.0,50.000000,0.000000,37.500000,0.000000,6.250000,0.000000,6.250000,0.000000
2,11.0,85.915493,5.633803,8.450704,0.000000,0.000000,0.000000,0.000000,0.000000
3,9.0,63.333333,6.666667,23.333333,3.333333,0.000000,0.000000,0.000000,3.333333
4,13.0,88.888889,0.000000,8.888889,2.222222,0.000000,0.000000,0.000000,0.000000
5,17.0,58.536585,7.317073,17.073171,14.634146,0.000000,0.000000,0.000000,2.439024
6,6.0,63.157895,2.631579,21.052632,7.894737,0.000000,0.000000,0.000000,5.263158
7,2.0,32.000000,4.000000,48.000000,4.000000,0.000000,0.000000,0.000000,12.000000
8,8.0,85.714286,2.857143,8.571429,0.000000,0.000000,0.000000,0.000000,2.857143
9,20.0,0.000000,50.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,9.0,6.666667,4.444444,22.222222,8.888889,4.444444,2.222222,0.000000,51.111111
11,10.0,6.779661,8.474576,16.949153,20.338983,1.694915,3.389831,0.000000,42.372881
12,15.0,6.250000,6.250000,28.125000,12.500000,0.000000,9.375000,0.000000,37.500000
13,16.0,12.352941,5.294118,19.411765,17.058824,2.352941,4.117647,1.764706,37.647059
14,17.0,1.960784,3.921569,17.647059,1.960784,0.000000,9.803922,0.000000,64.705882
15,18.0,11.764706,5.882353,0.000000,17.647059,0.000000,0.000000,5.882353,58.823529
16,19.0,11.320755,3.773585,22.641509,15.094340,0.000000,1.886792,1.886792,43.396226
17,23.0,2.173913,4.347826,30.434783,21.739130,0.000000,2.173913,4.347826,34.782609
18,24.0,2.439024,4.878049,18.292683,20.731707,2.439024,1.219512,0.000000,50.000000
19,30.0,0.000000,9.302326,9.302326,9.302326,0.000000,2.325581,0.000000,69.767442
20,31.0,12.500000,12.500000,2.500000,7.500000,12.500000,2.500000,2.500000,47.500000
21,36.0,6.962025,8.860759,17.721519,17.721519,4.430380,3.797468,1.898734,38.607595
22,38.0,15.584416,12.987013,25.974026,22.077922,2.597403,0.000000,0.000000,20.779221
23,39.0,7.142857,14.285714,25.000000,10.714286,0.000000,3.571429,0.000000,39.285714
24,42.0,12.222222,7.777778,17.777778,20.000000,2.222222,5.555556,2.222222,32.222222

In [12]:
early_counts = df_early["Counts_of_not_touching"]
late_counts = df_late["Counts_of_not_touching"]

combined = pd.concat([early_counts, late_counts],axis=1, 
                            keys=['Early_embryo','Late_embryo'])
combined

    Early_embryo  Late_embryo
0      48.000000    70.370370
1      76.744186    50.000000
2      40.000000    85.915493
3      52.173913    63.333333
4      50.000000    88.888889
5      93.023256    58.536585
6       3.448276    63.157895
7       3.448276    32.000000
8      13.888889    85.714286
9       0.000000     0.000000
10      8.620690     6.666667
11      0.000000     6.779661
12     15.217391     6.250000
13      2.325581    12.352941
14     11.864407     1.960784
15      0.000000    11.764706
16     21.621622    11.320755
17      4.347826     2.173913
18      0.000000     2.439024
19     13.888889     0.000000
20      5.555556    12.500000
21      0.000000     6.962025
22     19.117647    15.584416
23     16.666667     7.142857
24      0.000000    12.222222

In [13]:
from scipy.stats import mannwhitneyu

In [14]:
statistic, p_value = mannwhitneyu(combined["Early_embryo"],
                                  combined["Late_embryo"])

In [15]:
print("Mann-Whitney U statistic:", statistic)
print("p-value:", p_value)

Mann-Whitney U statistic: 261.5
p-value: 0.32615054791036024

In [16]:
df_early_dropped = df_early.drop("Embryo_ID", axis=1)
df_late_dropped = df_late.drop("Embryo_ID", axis=1)

In [56]:
for column in df_early_dropped.columns:
    early_counts = df_early_dropped[column]
    late_counts = df_late_dropped[column]
    
    combined = pd.concat([early_counts,late_counts],
                         axis=1, 
                         keys=['Early_embryo',
                               'Late_embryo'])
    statistic, p_value = mannwhitneyu(combined
                                      ["Early_embryo"],
                                      combined
                                      ["Late_embryo"])
    print("Column:",column)
    print("Mann-Whitney U statistic:", statistic)
    print("p-value:", p_value)

Column: Counts_of_not_touching
Mann-Whitney U statistic: 261.5
p-value: 0.32615054791036024
Column: Counts_3_prime_touch_5_prime
Mann-Whitney U statistic: 349.0
p-value: 0.483547415282473
Column: Counts_5_prime_touch_PPE
Mann-Whitney U statistic: 290.0
p-value: 0.6694494696186544
Column: Counts_3_prime_touch_PPE
Mann-Whitney U statistic: 270.0
p-value: 0.41322769826984884
Column: Counts_5_prime_middle
Mann-Whitney U statistic: 297.0
p-value: 0.730274307934341
Column: Counts_PPE_middle
Mann-Whitney U statistic: 264.0
p-value: 0.31029322753991717
Column: Counts_3_prime_middle
Mann-Whitney U statistic: 330.0
p-value: 0.6959977439892062
Column: Counts_all_touching
Mann-Whitney U statistic: 395.5
p-value: 0.10893299764725162

In [17]:
from scipy.stats import combine_pvalues

In [18]:
p_values_early_late = [0.32615054791036024,0.483547415282473,0.6694494696186544,0.41322769826984884,
            0.730274307934341,0.31029322753991717,0.6959977439892062,0.10893299764725162]
combined_p_value_early_late =combine_pvalues(p_values_early_late,method='fisher')

In [19]:
print (combined_p_value_early_late[1])

0.5695264102783979

In [21]:
file_path = '../PPE_late/PPE_percentages_per_embryo.csv'

df_PPE = pd.read_csv('../PPE_late/PPE_percentages_per_embryo.csv').drop(columns = 'Unnamed: 0')
df_PPE

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,1.0,9.708738,6.796117,19.417476,15.533981,0.970874,1.941748,0.000000,45.631068
1,2.0,2.884615,1.923077,10.576923,7.692308,0.000000,3.846154,0.000000,73.076923
2,3.0,3.703704,3.703704,11.111111,7.407407,1.851852,3.703704,0.000000,68.518519
3,4.0,0.000000,3.571429,21.428571,8.928571,0.000000,12.500000,1.785714,51.785714
4,5.0,2.222222,4.444444,8.888889,12.222222,3.333333,6.666667,0.000000,62.222222
5,6.0,7.865169,2.247191,15.730337,19.101124,3.370787,1.123596,2.247191,48.314607
6,7.0,5.319149,7.446809,11.702128,17.021277,3.191489,2.127660,1.063830,52.127660
7,43.0,13.333333,5.925926,9.629630,13.333333,2.222222,3.703704,0.000000,51.851852
8,44.0,8.536585,6.097561,19.512195,9.756098,3.658537,6.097561,0.000000,46.341463
9,45.0,32.653061,11.224490,18.367347,9.183673,1.020408,0.000000,0.000000,27.551020
10,46.0,45.614035,8.771930,21.491228,5.701754,2.192982,1.315789,0.438596,14.473684
11,48.0,15.000000,7.500000,21.785714,15.714286,0.357143,3.214286,0.000000,36.428571
12,49.0,18.840580,2.898551,33.333333,7.246377,2.898551,0.000000,0.000000,34.782609
13,50.0,17.721519,5.063291,11.392405,13.924051,2.531646,10.126582,1.265823,37.974684
14,51.0,1.052632,6.315789,16.842105,18.947368,0.000000,2.105263,0.000000,54.736842
15,52.0,34.920635,7.936508,12.698413,12.698413,1.587302,7.936508,0.000000,22.222222
16,53.0,17.142857,9.285714,12.142857,30.714286,0.714286,2.142857,0.000000,27.857143
17,54.0,6.976744,6.976744,16.279070,11.627907,4.651163,4.651163,4.651163,44.186047
18,55.0,15.053763,8.602151,12.903226,15.053763,0.000000,6.451613,0.000000,41.935484
19,66.0,10.465116,8.139535,19.186047,16.860465,1.162791,2.906977,1.744186,39.534884
20,67.0,6.349206,3.174603,12.698413,12.698413,0.000000,1.587302,0.000000,63.492063
21,68.0,0.000000,0.000000,20.000000,40.000000,0.000000,0.000000,0.000000,40.000000
22,69.0,8.888889,17.777778,20.000000,22.222222,0.000000,2.222222,0.000000,28.888889
23,70.0,12.500000,20.833333,4.166667,16.666667,4.166667,0.000000,0.000000,41.666667
24,71.0,5.263158,0.000000,23.684211,10.526316,2.631579,2.631579,0.000000,55.263158

In [22]:
df_PPE_dropped = df_PPE.drop("Embryo_ID", axis=1)
df_late_dropped = df_late.drop("Embryo_ID", axis=1)

In [23]:
combined_results = pd.DataFrame()

for column in df_PPE_dropped.columns:
    PPE_counts = df_PPE_dropped[column]
    late_counts = df_late_dropped[column]
    combined_PPE = pd.concat([PPE_counts, late_counts], 
                              axis =1,
                              keys = ['PPE', 'Late'])
    statistic, p_value = mannwhitneyu(combined_PPE["PPE"], 
                                      combined_PPE["Late"])
    combined_results[column] = pd.Series({"Mann-Whitney U statistic": statistic, 
                                          "p-value":p_value})
    print("Column:", column)
    print("Mann-Whitney U statistic:", statistic)
    print("p-value:", p_value)
    print()

Column: Counts_of_not_touching
Mann-Whitney U statistic: 251.5
p-value: 0.2403219042221605

Column: Counts_3_prime_touch_5_prime
Mann-Whitney U statistic: 321.5
p-value: 0.8689381236661127

Column: Counts_5_prime_touch_PPE
Mann-Whitney U statistic: 235.5
p-value: 0.13769621963917283

Column: Counts_3_prime_touch_PPE
Mann-Whitney U statistic: 391.0
p-value: 0.130070950134393

Column: Counts_5_prime_middle
Mann-Whitney U statistic: 393.5
p-value: 0.1001971795364133

Column: Counts_PPE_middle
Mann-Whitney U statistic: 412.5
p-value: 0.04964683783092132

Column: Counts_3_prime_middle
Mann-Whitney U statistic: 283.0
p-value: 0.4876078888673824

Column: Counts_all_touching
Mann-Whitney U statistic: 444.5
p-value: 0.010687243303187216

In [24]:
p_values_PPE = [0.2403219042221605,0.8689381236661127,0.13769621963917283,
            0.130070950134393,0.1001971795364133,0.04964683783092132,
            0.4876078888673824,0.010687243303187216]
combined_p_value_PPE =combine_pvalues(p_values_PPE,method='fisher')

In [25]:
print (combined_p_value_PPE[1])

0.00914306826219727

In [27]:
file_path = '../Twist_comparison/Twist_txt/YW/twist_YW_percentage.csv'
df_YW_twist = pd.read_csv('../Twist_comparison/Twist_txt/YW/twist_YW_percentage.csv').drop(columns = 'Unnamed: 0')
df_YW_twist

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,16.0,15.942029,2.898551,18.840580,18.840580,4.347826,5.797101,1.449275,31.884058
1,17.0,0.000000,4.545455,15.909091,2.272727,0.000000,11.363636,0.000000,65.909091
2,18.0,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,25.000000,50.000000
3,19.0,11.627907,20.930233,6.976744,23.255814,0.000000,4.651163,0.000000,32.558140
4,23.0,2.439024,4.878049,29.268293,26.829268,0.000000,2.439024,4.878049,29.268293
5,36.0,5.882353,11.764706,17.647059,29.411765,5.882353,5.882353,0.000000,23.529412
6,38.0,25.925926,18.518519,25.925926,3.703704,0.000000,0.000000,0.000000,25.925926
7,42.0,13.333333,13.333333,13.333333,20.000000,6.666667,6.666667,6.666667,20.000000

In [28]:
file_path = '../Twist_comparison/No_twist_txt/YW/No_twist_YW_percentages.csv'
df_YW_no_twist = pd.read_csv('../Twist_comparison/No_twist_txt/YW/No_twist_YW_percentages.csv').drop(columns = 'Unnamed: 0')
df_YW_no_twist

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,16.0,6.382979,4.255319,17.021277,14.893617,2.127660,4.255319,2.12766,48.936170
1,17.0,14.285714,0.000000,28.571429,0.000000,0.000000,0.000000,0.00000,57.142857
2,18.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,100.000000
3,19.0,23.529412,0.000000,29.411765,0.000000,0.000000,5.882353,0.00000,41.176471
4,23.0,0.000000,0.000000,50.000000,0.000000,0.000000,0.000000,0.00000,50.000000
5,36.0,11.764706,17.647059,23.529412,5.882353,0.000000,5.882353,0.00000,35.294118
6,38.0,3.571429,14.285714,28.571429,32.142857,3.571429,0.000000,0.00000,17.857143
7,42.0,12.765957,6.382979,19.148936,19.148936,2.127660,8.510638,0.00000,31.914894

In [29]:
df_YW_twist_dropped = df_YW_twist.drop("Embryo_ID", axis=1)
df_YW_no_twist_dropped = df_YW_no_twist.drop("Embryo_ID", axis=1)

In [30]:
combined_results = pd.DataFrame()

for column in df_YW_twist_dropped.columns:
    YW_twi_counts = df_YW_twist_dropped[column]
    YW_no_twi_counts = df_YW_no_twist_dropped[column]
    combined_YW_twi = pd.concat([YW_twi_counts, YW_no_twi_counts], 
                              axis =1,
                              keys = ['YW_twi', 'YW_no_twi'])
    statistic, p_value = mannwhitneyu(combined_YW_twi["YW_twi"], 
                                      combined_YW_twi["YW_no_twi"])
    combined_results[column] = pd.Series({"Mann-Whitney U statistic": statistic, 
                                          "p-value":p_value})
    print("Column:", column)
    print("Mann-Whitney U statistic:", statistic)
    print("p-value:", p_value)

Column: Counts_of_not_touching
Mann-Whitney U statistic: 32.0
p-value: 1.0
Column: Counts_3_prime_touch_5_prime
Mann-Whitney U statistic: 50.0
p-value: 0.0640930207850402
Column: Counts_5_prime_touch_PPE
Mann-Whitney U statistic: 17.5
p-value: 0.14089641314435308
Column: Counts_3_prime_touch_PPE
Mann-Whitney U statistic: 44.0
p-value: 0.2202347585707377
Column: Counts_5_prime_middle
Mann-Whitney U statistic: 36.5
p-value: 0.628967844730379
Column: Counts_PPE_middle
Mann-Whitney U statistic: 39.0
p-value: 0.48199557532062365
Column: Counts_3_prime_middle
Mann-Whitney U statistic: 45.0
p-value: 0.11046513041143856
Column: Counts_all_touching
Mann-Whitney U statistic: 19.5
p-value: 0.2072440909861849

In [31]:
print(combined_YW_twi)

      YW_twi   YW_no_twi
0  31.884058   48.936170
1  65.909091   57.142857
2  50.000000  100.000000
3  32.558140   41.176471
4  29.268293   50.000000
5  23.529412   35.294118
6  25.925926   17.857143
7  20.000000   31.914894

In [32]:
twi_YW_p_values = [0.8940261192428913,0.0833181819350908,0.1706562821472032,
            0.326343475596656, 0.4669159252764402,0.41724407453644374,
            0.11769344517777437,0.28831753089610856]
combined_p_values_YW_twi =combine_pvalues(twi_YW_p_values,method='fisher')

In [33]:
print (combined_p_values_YW_twi[1])

0.17819772308910103

In [34]:
file_path = '../Twist_comparison/Twist_txt/PPE/PPE_percentages.csv'
df_PPE_twist = pd.read_csv('../Twist_comparison/Twist_txt/PPE/PPE_percentages.csv').drop(columns = 'Unnamed: 0')
df_PPE_twist

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,1.0,5.000000,15.000000,5.000000,20.000000,5.000000,5.000000,0.000000,45.000000
1,3.0,0.000000,10.000000,10.000000,0.000000,0.000000,10.000000,0.000000,70.000000
2,4.0,0.000000,2.631579,18.421053,7.894737,0.000000,13.157895,2.631579,55.263158
3,5.0,11.111111,0.000000,22.222222,11.111111,11.111111,0.000000,0.000000,44.444444
4,43.0,20.560748,5.607477,13.084112,11.214953,2.803738,4.672897,0.000000,42.056075
5,45.0,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000
6,46.0,42.857143,15.966387,15.966387,9.243697,1.680672,0.000000,2.521008,11.764706
7,51.0,0.000000,4.761905,14.285714,19.047619,0.000000,4.761905,0.000000,57.142857
8,55.0,0.000000,0.000000,42.857143,0.000000,0.000000,0.000000,0.000000,57.142857

In [44]:
file_path = '../Twist_comparison/No_twist_txt/PPE/PPE_percentages_no_twi.csv'
df_PPE_no_twist = pd.read_csv('../Twist_comparison/No_twist_txt/PPE/PPE_percentages_no_twi.csv').drop(columns = 'Unnamed: 0')
df_PPE_no_twist

,Embryo_ID,Counts_of_not_touching,Counts_3_prime_touch_5_prime,Counts_5_prime_touch_PPE,Counts_3_prime_touch_PPE,Counts_5_prime_middle,Counts_PPE_middle,Counts_3_prime_middle,Counts_all_touching
0,1.0,14.583333,2.083333,14.583333,18.750000,0.000000,2.083333,0.000000,47.916667
1,3.0,10.000000,0.000000,40.000000,0.000000,0.000000,0.000000,0.000000,50.000000
2,4.0,0.000000,8.695652,30.434783,4.347826,0.000000,13.043478,4.347826,39.130435
3,5.0,0.000000,3.125000,15.625000,6.250000,3.125000,6.250000,0.000000,65.625000
4,43.0,14.893617,6.382979,10.638298,14.893617,4.255319,4.255319,0.000000,44.680851
5,45.0,28.571429,21.428571,14.285714,21.428571,0.000000,0.000000,0.000000,14.285714
6,46.0,42.574257,8.910891,22.772277,2.970297,3.960396,2.970297,0.000000,15.841584
7,51.0,0.000000,0.000000,41.176471,23.529412,0.000000,0.000000,0.000000,35.294118
8,55.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000

In [45]:
df_PPE_twist_dropped = df_PPE_twist.drop("Embryo_ID", axis=1)
df_PPE_no_twist_dropped = df_PPE_no_twist.drop("Embryo_ID", axis=1)

In [81]:
combined_results = pd.DataFrame()

for column in df_PPE_twist_dropped.columns:
    PPE_twi_counts = df_PPE_twist_dropped[column]
    PPE_no_twi_counts = df_PPE_no_twist_dropped[column]
    combined_PPE_twi = pd.concat([PPE_twi_counts, PPE_no_twi_counts], 
                              axis =1,
                              keys = ['PPE_twi', 'PPE_no_twi'])
    statistic, p_value = mannwhitneyu(combined_PPE_twi["PPE_twi"], 
                                      combined_PPE_twi["PPE_no_twi"])
    combined_results[column] = pd.Series({"Mann-Whitney U statistic": statistic, 
                                          "p-value":p_value})
    print("Column:", column)
    print("Mann-Whitney U statistic:", statistic)
    print("p-value:", p_value)

Column: Counts_of_not_touching
Mann-Whitney U statistic: 42.0
p-value: 0.9263819981954123
Column: Counts_3_prime_touch_5_prime
Mann-Whitney U statistic: 42.5
p-value: 0.8926813430946551
Column: Counts_5_prime_touch_PPE
Mann-Whitney U statistic: 31.0
p-value: 0.4262989701297739
Column: Counts_3_prime_touch_PPE
Mann-Whitney U statistic: 37.0
p-value: 0.7889430711187748
Column: Counts_5_prime_middle
Mann-Whitney U statistic: 45.0
p-value: 0.6878704749917823
Column: Counts_PPE_middle
Mann-Whitney U statistic: 46.0
p-value: 0.6440892579580211
Column: Counts_3_prime_middle
Mann-Whitney U statistic: 44.0
p-value: 0.6834580299010776
Column: Counts_all_touching
Mann-Whitney U statistic: 48.5
p-value: 0.5073621344473913

In [36]:
PPE_twi_p_values = [1.0,0.4753370978324023,0.5075815363784091,0.722555580225112,
            0.497401877793916,0.4667609060908846,0.6834580299010776,0.7909761303269929]
combined_p_value_PPE_twi =combine_pvalues(PPE_twi_p_values,method='fisher')

In [37]:
print (combined_p_value_PPE_twi[1])

0.958756574917517